### ISSUE TITLE
Bilder i artikler

### ISSUE THREAD

**Issue by batfink** [askoyfk/askoyfk.github.io#51]
Bilder bør hostes et sted som tilbyr skaleringsmuligheter, slik at vi kan bruke det nye responsive picture-elementet (med [polyfill](http://scottjehl.github.io/picturefill/) for nettlesere som ikke støtter det ennå) og få responsive bilder.

Noen alternativer: 
- https://www.imgix.com
- http://cloudinary.com
- http://www.resrc.it

Så kan vi legge til en frontmatter property for bilder, som blir et array der det første bildet blir hovedbildet til artikkelen. Dette vil f.eks. kunne gå over hele sidebredden, mens øvrige bilder vil kunne legges i et sidepanel. 

Syntaxen for dette vil kunne se slik ut: 

```yaml
---
title: Askøy Fotballklubb - En positiv opplevelse
layout: post
author: Kjetil Sørtun, Sportslig leder
images: 
  - 
    url: url_til_cdn/bilde1.jpg
    caption: Bildetekst til bildet
  -
    url: url_til_cdn/bilde2.jpg
    caption: Bildetekst til bildet
---
```
